/*
 * This source file was generated by the Gradle 'init' task
 */
package hoge5;
import java.awt.*;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayDeque;
import javax.imageio.ImageIO;

public class Main extends Frame implements ActionListener{

 public static TextArea text = new TextArea();
 public static Label label = new Label();
 public static Label label3= new Label();
 public static Label label2= new Label();
 public static Card card2 = new Card();
 
 public static ArrayDeque<String> card = new ArrayDeque<String>(52);   
  public static void main(String[] args) throws Exception {
        ReadImageComponent image = new ReadImageComponent();
        Color col2 = new Color(0,0,0);
        Color col3 = new Color(200,0,0);
        Frame frame = new Frame();
        frame.setAlwaysOnTop(true);
        frame.setBackground(col2);
        String imageFilename = "C:/hoge/hoge5/app/src/main/java/hoge5/tamago.png";
        Image img = ImageIO.read(new File(imageFilename));
        frame.setIconImage(img);
        frame.addWindowListener ( new WindowAdapter () {
            public void windowClosing (WindowEvent we) {
                System.exit(0);
            }
        });
        frame.setTitle("雑用");
        frame.setSize(580 ,480);

        GridBagLayout gnt = new GridBagLayout(); 
        GridBagConstraints cont = new GridBagConstraints();
        frame.setLayout(gnt);
        
        text.setPreferredSize(new Dimension(200, 150));
        text.setVisible(true);
        cont.gridx = 0;
        cont.gridy = 1;
        cont.gridheight =1;
        cont.gridwidth = 1;
        cont.insets=new Insets(0,50,50,0);
        gnt.setConstraints(text, cont);
        frame.add(text);
        frame.setVisible(true);
        
        label.setText("");
        label.setForeground(col3);
        label.setFont(new Font("SANS_SERIF", 20, 20));
        label.setPreferredSize(new Dimension(200,30));
        label.setVisible(true);
        cont.gridx =1;
        cont.gridy =1;
        cont.gridheight =1;
        cont.gridwidth = 1;
        cont.insets = new Insets(0, 0, -50,50);
        gnt.setConstraints(label,cont);
        frame.add(label);


        

        Button btn3 = new Button("表示");
        btn3.setPreferredSize(new Dimension(50,50));
        cont.gridx = 0;
        cont.gridy = 0;
        cont.gridheight = 1;
        cont.gridwidth = 0;
        cont.insets = new Insets(150, 0, 0, 110);
        gnt.setConstraints(btn3, cont);
        frame.add(btn3);
        btn3.setVisible(true);
        

        Button btn2 = new Button("コピー");
        btn2.setPreferredSize(new Dimension(150,50));
        cont.gridx = 0;
        cont.gridy = 0;
        cont.gridheight = 1;
        cont.gridwidth = -1;
        cont.insets = new Insets(150, 0, 0, 0);
        gnt.setConstraints(btn2, cont);
        btn2.setVisible(true);
        frame.add(btn2);
        Button btn4 = new Button("貼付");
        btn4.setPreferredSize(new Dimension(104,30));
        btn4.setVisible(true);
         cont.gridx = 1;
        cont.gridy = 0;
        cont.gridheight = 2;
        cont.gridwidth = -4;
        cont.insets = new Insets(70, -8, 0, 200);
        gnt.setConstraints(btn4, cont);
        frame.add(btn4);
        cont.gridx = 1;
        cont.gridy = 0;
        cont.gridheight =2;
        cont.gridwidth = -5;
        cont.insets = new Insets(0, 0, 0, 210);
        gnt.setConstraints(image, cont);
        frame.add(image);
        
        label2.setText("");
        label2.setFont(new Font("SANS_SERIF",20,20));
        label2.setPreferredSize(new Dimension(200,30));
        label2.setVisible(true);
        label2.setForeground(col3);
        cont.gridx = 1;
        cont.gridy = 1;
        cont.gridheight =1;
        cont.gridwidth = 1;
        cont.insets = new Insets(100, 0, -100, 50);
        gnt.setConstraints(label2, cont);
        frame.add(label2);
        
        label3.setText("");
        label3.setFont(new Font("SANS_SERIF",20,20));
        label3.setPreferredSize(new Dimension(200,30));
        label3.setVisible(true);
        label3.setForeground(col3);
        cont.gridx = 1;
        cont.gridy = 1;
        cont.gridheight =1;
        cont.gridwidth = 1;
        cont.insets = new Insets(150, 0, 0, 50);
        gnt.setConstraints(label3, cont);
        frame.add(label3);
        btn3.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e){
            Dialog d = new Dialog(new hoge(new Main()),"ぽっぷあっぷ",true);

           } 
        });
        btn2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){

                Clipboard crip = Toolkit.getDefaultToolkit().getSystemClipboard();
                StringSelection select = new StringSelection(text.getText());
                crip.setContents(select, null);

            }
        });
        

     
        
        
        btn4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                
                try {
                    Robot robot = new Robot();
                    robot.mouseMove(500, 1000);
                    robot.mousePress(MouseEvent.BUTTON1_DOWN_MASK);
                    robot.mouseRelease(MouseEvent.BUTTON1_DOWN_MASK);
                    robot.keyPress(KeyEvent.VK_CONTROL);
                    robot.keyPress(KeyEvent.VK_V);
                    robot.keyRelease(KeyEvent.VK_V);
                    robot.keyRelease(KeyEvent.VK_CONTROL);
                    robot.keyPress(KeyEvent.VK_ENTER);
                    robot.keyRelease(KeyEvent.VK_ENTER);
                    robot.mouseMove(990, 540);
                } catch (AWTException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                }
            }
        });
        text.addKeyListener(new KeyListener() {
            public void keyPressed(KeyEvent e){
                if(e.getKeyCode() == KeyEvent.VK_ENTER){
                    if(Main.text.getText().contains("wav変換")){
                    int x = Main.text.getText().indexOf("\n");
                    x = x-1;
                    String h = Main.text.getText().substring(0,x);
                    h = "C:/Users/akuta/Downloads/"+h;
try {
// ffmpegコマンドを定義します
String ffmpegCmd = "ffmpeg -i " + h + " C:/Users/akuta/Downloads/hoge.wav";

// ffmpegコマンドを実行します
Process process = null;
try {
    process = Runtime.getRuntime().exec(ffmpegCmd);
} catch (IOException e1) {
    // TODO Auto-generated catch block
    e1.printStackTrace();
}

// コマンドの実行が完了するまで待ちます
}
finally{


}

                    }
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }

            @Override
            public void keyTyped(KeyEvent e) {
            }
        });
        
        card = card2.setDeck();
        Main2 main2 = new Main2();
        main2.start();
        Main3 main3 = new Main3();
        main3.start(); 
        Main4 main4 = new Main4();
        main4.start();
        Main5 main5 = new Main5();
        main5.start();
        frame.setVisible(true);
        
        
    }
  @Override
  public void actionPerformed(ActionEvent e) {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("Unimplemented method 'actionPerformed'");
  }
  public Object getGreeting() {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("Unimplemented method 'getGreeting'");
  }
    
    }